cc_library(
    name = "tba",
    srcs = ["tba.cpp"],
    hdrs = ["tba.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/include/json",
        "//src/protos:models_cpp",
        "//src/protos:tpa_cpp",
        "@cpr",
    ],
)
